### ISSUE TITLE
Success with ESP32 hardware AP MEMORY / 6404L-350R / 1120A / 130027G

### ISSUE THREAD

**Issue by Jandaduns** [jomjol/AI-on-the-edge-device-docs#10]
Just wanted to let you know that I was able to correctly flash (and use) an ESP32 CAM module with the label 'AP MEMORY / 6404L-350R / 1120A / 130027G' on the PSRAM module. Perhaps you can update the hardware compatibility page to reflect this. It showed 8Mb of RAM. https://jomjol.github.io/AI-on-the-edge-device-docs/Hardware-Compatibility/

**Comment by caco3** [comment]
That list is not really up-to-date anymore.
We better would remove it. Its better to use the discussion page at https://github.com/jomjol/AI-on-the-edge-device/discussions/1732

Can you add your experience there?

**Comment by Jandaduns** [comment]
Added it to the discussion page as @caco3 suggested. Closed the ticket.
