### ISSUE TITLE
Local cloning with GitHub Desktop not working anymore.

### ISSUE THREAD

**Issue by jomjol** [jomjol/AI-on-the-edge-device-docs#17]
I cannot clone this repo anymore for a local copy with GitHub Desktop. 
Following error message after a complete deletion and new setup:

![grafik](https://user-images.githubusercontent.com/30766535/217913762-3902fb66-75d4-489d-99f1-5d0e1fb06cc5.png)

**Comment by caco3** [comment]
I think it something to do that Windows does not allow `<` in filenames. On Linux it works ok.
I will rename those files...

**Comment by caco3** [comment]
It should now also work on windows.

To create a parameter documentation, you either can:
- Auto generate it:
    1. update `/sd-card/config/config.ini` in the main repo
    2. run `generate-param-doc-pages.py` inside `param-docs`.
      This will generate a new templated file in `parameter-pages/<SECTION>/<PARAMETER.md>
    3. Update the generated file and check it into git
- Manually generate it:
  1. create the file ``parameter-pages/<SECTION>/<PARAMETER.md>` and fil lit as needed, but please adapt the format of the other pages.
  2. check it into git

To test it locally, call `concat-parameter-pages.py` inside `param-docs` to generate the combined `parameter.md` page.
Then call `mkdocs serve` and open http://127.0.0.1:8000/AI-on-the-edge-device-docs/Parameters/ in your webbrowser to test it.

**Comment by caco3** [comment]
See the readme.md for more details

**Comment by jomjol** [comment]
Is now working - thanks for the fix
