### ISSUE TITLE
No Folder "sdcard/img_tmp/"

### ISSUE THREAD

**Issue by Rik74** [jomjol/AI-on-the-edge-device-docs#22]
Ich habe beim konfigurieren erhebliche Probleme gehabt, wie zb das keine Referenzbilder auf der SD-Karte gespeichert wurden.
Das Logfile teilte dann mit, dass es das Bild nicht in
sdcard/img_tmp/
erstellen konnte.

Da das Verzeichnis nicht existierte habe ich es manuell erstellt, die Konfiguration war danach ohne Probleme möglich

**Comment by caco3** [comment]
Da fehlen mir ganz viele Informationen!
Zudem ist es besser, im Software-Repo einen Bug zu schrieben anstatt hier. Hier wird nur die Doku verwaltet.

=> https://github.com/jomjol/AI-on-the-edge-device/issues/new?assignees=&labels=bug&template=bug_report.yml
