### ISSUE TITLE
document "value to high" and set pre value

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device-docs#23]

**Comment by haverland** [comment]
@caco3 @jomjol : We have now Configuration.md and for the part "Postprocessing" "Correction Algorithm.md"

Im wondering what the best case is. Reference in Configuration.md to Correction Algorithm.md or integrate it in Configuration.md?

**Comment by caco3** [comment]
my idea was to have a nice landing page for "neg rate" or "rate to high", since this often is an issue for users.
with separate URLs for them we could easier link to them in the discussions.

**Comment by haverland** [comment]
OK. Create two .md's
