### ISSUE TITLE
Influxdb1 config uses V2 api calls

### ISSUE THREAD

**Issue by srLinux** [jomjol/AI-on-the-edge-device-docs#26]
Hi,

I have configured InfluxDBv1 and it does not work. I checked the logs and noticed that the API URI: is http://192.168.10.17:8086/api/v2/write?bucket=test/ which looks like it is for v2 type of database.

**Comment by caco3** [comment]
what was your issue?

**Comment by srLinux** [comment]
good morning, posted my issue in the right repo, https://github.com/jomjol/AI-on-the-edge-device/issues/2203
sorry.
Would it be ok to close it here? then let me know :-)

**Comment by caco3** [comment]
yep, thats great!
