### ISSUE TITLE
Docs are linking to wrong repository

### ISSUE THREAD

**Issue by Lackmake** [jomjol/AI-on-the-edge-device-docs#43]
The description how to train your own models links to a wrong repository i think.
The first sentence in Chapter "1.0.2 dig-class100 / dig-cont models (digits)" says to checkout and links to the "analog"-training-repo but it should link to the "Tenth-of-step-of-a-meter-digit"-repo if i unterstand correctly.

Die Anleitung zum Trainieren eigener Modelle verlinkt auf das analog-Repo, sollte aber auf das "Tenth-of-step-of-a-meter-digit" Repo verlinken.

**Comment by haverland** [comment]
Thx for describe.
